### PR TITLE
make option `targets` optional

### PR DESCRIPTION
**Pull request by christophehurpeau**

### CODE REVIEW

**Comment by ArnaudRinquin** [comment]
Merged and published as `v1.1.1`

Thanks again for your contribution!

I'm curious about how and why you use this module, mind to tell me?

**Comment by christophehurpeau** [comment]
Thanks !

We use it [to remove imports only used on server-side (or client-side or dev only)](https://github.com/Evaneos/vitaminjs/blob/14199781620a037cc49b5a93e747765db0c04017/config/build/babelrc.js#L50). I also use it on several personal projects for the same reason.

**Comment by christophehurpeau** [comment]
@ArnaudRinquin it seems that the lib in the published version `1.1.1` was not modified

**Comment by ArnaudRinquin** [comment]
Ah? That's weird. Let me check.

**Comment by ArnaudRinquin** [comment]
Entirely my fault, I'll fix that and make sure it never happens again.

**Comment by ArnaudRinquin** [comment]
Fix and deploy as `v1.1.2`.

I made sure this issue never happens again in 04f612a650fc62952c7d7f02d808e6c7feb28ce4.

**Comment by christophehurpeau** [comment]
Thanks !

**Pull request merged**
